package com.example.demo.entity.enums;

public enum PermissionEnums {
	// USER
	ADD_USER,
	EDIT_USER,
	EDIT_USER_STATUS,
	DELETE_USER,
	VIEW_USER_LIST,
	VIEW_USER,
	EDIT_USER_PASSWORD,
	
	// Role
	ADD_ROLE,
	EDIT_ROLE,
	DELETE_ROLE,
	VIEW_ROLE,
	VIEW_ROLE_LIST,
	VIEW_ROLE_PERMISSIONS,
	ADD_PERMISSION_TO_ROLE,
	DELETE_PERMISSION_FROM_ROLE,
	
	// Permission
	ADD_PERMISSION,
	EDIT_PERMISSION,
	VIEW_PERMISSION_LIST,
	DELETE_PERMISSION
}
